# coding=utf-8
import yagmail
import time
from datetime import datetime
# CREATING A FILE WITH THE DAY OF THE BACKUP LIKE 2020-02-10-BACKUPFILENAME.TAR.GZ
now = datetime.now()
date = now.strftime("%Y-%m-%d")
filename = date + '-invoiceninja-db.tar.gz'
filename_path= '/backups/' + filename
# FOR GMAIL SENDER ACCOUNT NEED TO ACTIVATED THE UNSECURE APP AUTORIZATION: GO https://myaccount.google.com/security SEARCH FOR Access to less secure apps AND ENABLE IT
sender_mail = "your.unsecured@gmail.com"
sender_password = "Gmail-Password"
receiver = "put.receiver@gmail.com" 
contents = [
  "EMAIL CONTENTS",
  "You can put row in your email body like this",
  "Every row have "" and a , at the end",
  "An automatic message generated by a PYBot"  
]
# END SENDER RECEIVER EMAIL EDITING
yagmail.register(sender_mail, password=sender_password)
yag = yagmail.SMTP(sender_mail, password=sender_password)

yag.send(
	to="trendcolorsagl@gmail.com",
	subject="Il tuo backup DB mensile di fatture-trendcolor-net",
	contents=contents,
	attachments=filename_path,
)
