# coding=utf-8
import yagmail
import time
from datetime import datetime

# SCRIPT EMAIL WITH ATTACHMENT TO A RECEIVER USING GMAIL SMTP SERVER

#  LOCATE A FILE WITH THE DAY OF THE BACKUP LIKE 2020-02-10-BACKUPFILENAME.TAR.GZ
now = datetime.now()
date = now.strftime("%Y-%m-%d")
filename = date + '-backupfilename.tar.gz'
filename_path= '/backups/' + filename
# FOR GMAIL SENDER ACCOUNT NEED TO ACTIVATED THE UNSECURE APP AUTORIZATION: GO https://myaccount.google.com/security SEARCH FOR Access to less secure apps AND ENABLE IT
sender_mail = "your.unsecured@gmail.com"
sender_password = "Gmail-Password"
receiver = "put.receiver@gmail.com" 
subject = "Your email subject"
contents = [
  "EMAIL CONTENTS",
  "You can put row in your email body like this",
  "Every row have "" and a , at the end",
  "An automatic message generated by a PYBot"  
]
# END SENDER RECEIVER EMAIL EDITING

# START SEND EMAIL
yag = yagmail.SMTP(sender_mail, password=sender_password)

yag.send(
	to=receiver,
	subject=subject,
	contents=contents,
	attachments=filename_path,
)
